#!/usr/bin/env bash
# =============================================================================
#  generate-keystore.sh
# -----------------------------------------------------------------------------
#  Generates the ONE-AND-ONLY Android signing keystore for the AIGames FPS
#  prototype and writes a git-ignored keystore.properties that the Unity build
#  pipeline consumes automatically.
#
#  WHY THIS MATTERS (seamless APK updates):
#    Android only installs an APK as an *update* (instead of demanding an
#    uninstall) when ALL of the following hold for the new build:
#       1. identical applicationId          -> com.aigames.fpsprototype (fixed)
#       2. signed with the SAME key          -> THIS keystore, forever
#       3. a strictly higher versionCode     -> auto-incremented by the build
#
#    => Therefore this script REFUSES to overwrite an existing keystore. If you
#       lose this file you can never ship a seamless update again; every user
#       would have to uninstall first. BACK IT UP somewhere safe & private.
#
#  Usage:
#       ./scripts/generate-keystore.sh                 # interactive-ish defaults
#       STORE_PASS=... KEY_PASS=... ./scripts/generate-keystore.sh   # CI / non-TTY
# =============================================================================
set -euo pipefail

# --- Resolve paths relative to the project root (parent of this script) ------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
KEYSTORE_DIR="${PROJECT_ROOT}/keystore"
KEYSTORE_FILE="${KEYSTORE_DIR}/aigames-release.keystore"
PROPS_FILE="${KEYSTORE_DIR}/keystore.properties"

# --- Configurable identity (override via env) --------------------------------
KEY_ALIAS="${KEY_ALIAS:-aigames}"
VALIDITY_DAYS="${VALIDITY_DAYS:-10950}"   # ~30 years; the key must outlive the app
DNAME="${DNAME:-CN=AI Games, OU=Mobile, O=AI Games, L=Berlin, S=Berlin, C=DE}"

mkdir -p "${KEYSTORE_DIR}"

# --- Hard guard: never clobber an existing key -------------------------------
if [[ -f "${KEYSTORE_FILE}" ]]; then
  echo "✗ Keystore already exists: ${KEYSTORE_FILE}"
  echo "  Refusing to overwrite — reusing the same key is REQUIRED for seamless updates."
  echo "  Delete it manually only if you fully understand the consequences."
  exit 0
fi

# --- Locate keytool ----------------------------------------------------------
if ! command -v keytool >/dev/null 2>&1; then
  echo "✗ 'keytool' not found. Install a JDK (e.g. the one bundled with Unity:"
  echo "    <UnityEditor>/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK/bin)"
  echo "  and ensure keytool is on your PATH."
  exit 1
fi

# --- Resolve passwords (env -> generated) ------------------------------------
gen_pass() { head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 20; }
STORE_PASS="${STORE_PASS:-$(gen_pass)}"
KEY_PASS="${KEY_PASS:-${STORE_PASS}}"

echo "→ Generating keystore: ${KEYSTORE_FILE}"
keytool -genkeypair \
  -alias "${KEY_ALIAS}" \
  -keyalg RSA \
  -keysize 2048 \
  -validity "${VALIDITY_DAYS}" \
  -keystore "${KEYSTORE_FILE}" \
  -storepass "${STORE_PASS}" \
  -keypass "${KEY_PASS}" \
  -dname "${DNAME}" \
  -storetype PKCS12

# --- Write the git-ignored properties file the build pipeline reads ----------
umask 077
cat > "${PROPS_FILE}" <<EOF
# AUTO-GENERATED by scripts/generate-keystore.sh — DO NOT COMMIT.
storeFile=keystore/aigames-release.keystore
storePassword=${STORE_PASS}
keyAlias=${KEY_ALIAS}
keyPassword=${KEY_PASS}
EOF
chmod 600 "${PROPS_FILE}"

cat <<EOF

✓ Keystore created and registered.
    keystore : ${KEYSTORE_FILE}
    config   : ${PROPS_FILE}  (git-ignored)
    alias    : ${KEY_ALIAS}

⚠  BACK UP both files NOW to a secure, private location (password manager /
   secrets vault). They are intentionally git-ignored. If you lose them you can
   never publish a seamless update for com.aigames.fpsprototype again.

Next: open the project in Unity and the build pipeline will pick these up
      automatically (see Assets/Editor/AIGamesBuild/BuildScript.cs).
EOF
